# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

def shared_pods
    pod "Makemoji-SDK", :path => '../.'
end

target 'MakemojiSDKDemo' do
    shared_pods
end

target 'Tests' do
    shared_pods
    pod 'OCMock', '~> 3.4'
end
